#!/usr/bin/env python3
import sys
sys.dont_write_bytecode = True
from googleLib import groupList
from googleLib import getCredentials

def main():
  l = len(sys.argv)
  if l == 2:
    try:
      groupDump = groupList(sys.argv[1])
    except:
      print('Please provide a valid email address.  For example:')
      print('./groupList <email address>')
      exit()
  else:
    print('Wrong number of arguments specified, require only 1')
    print('Please provide a valid email address.  For example:')
    print('./groupList <email address>')
    exit()
  for x in groupDump:
    groupEmail = x['email']
    groupName = x['name']
    print(groupEmail, '(', groupName, ')')

if __name__ == '__main__':
  main()
